import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { PostCard, Categories, PostWidget } from './components'

const inter = Inter({ subsets: ['latin'] })
const posts = [
  { title: 'The Spiritual Journey', excerpt: 'The awakening of my journey' },
  { title: 'Jane Eyre: Not a Cinderella Story', excerpt: 'Resume of the legendary novel by Charlotte Bronte, Jane Eyre' },
];
export default function Home() {
  return (

    <div className='container mx-auto px-10 mb-8'>
      <Head>
        <title>The Jour</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
        <div className='lg:col-span-8 col-span-1'>
          {posts.map((post) => <PostCard post = {post} key={post.title} />)}
        </div>
        <div className='lg:col-span-4 col-span-1'>
            <div className='lg:sticky relative top-8'>
            <PostWidget />
            <Categories />
            </div>
        </div>
      </div>
    </div>
  )
}
