import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { PostCard, Categories, PostWidget } from '../components'
import { getPosts } from '../services';
import { FeaturedPosts } from '../sections'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ posts }) {
  return (

    <div className='container mx-auto px-10 mb-8'>
      <Head>
        <title>The Jour</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type='image/png' href="/logo2.png" />
      </Head>
      <FeaturedPosts />
      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
        <div className='lg:col-span-8 col-span-1'>
          {posts.map((post) => <PostCard post = {post.node} key={post.title} />)}
        </div>
        <div className='lg:col-span-4 col-span-1'>
            <div className='lg:sticky relative top-8'>
            <PostWidget />
            <Categories />
            </div>
        </div>
      </div>
    </div>
  )
}

export async function getStaticProps(){
  const posts = (await getPosts()) || [];

  return{
    props: {posts}
  }
}